Update the README.md file to describe the repo.
Prem20560404/software-product-sprint pull request #1
Opened 2022-05-25 22:06 UTC by Prem20560404

I completed the week 0 - setup and I am requesting a pull request.

2022-06-01 05:40 UTC, Prem20560404 commented
I am working on week 1 project. I added image to portfolio.

2022-06-02 17:15 UTC, IslandCow requested changes
Looks pretty good.  I found a typo and I left a few comments regarding spacing.

2022-06-02 17:15 UTC, IslandCow commented on portfolio/src/main/webapp/index.html
> +            Developed a GUI Interface that ask the user for personal informations, such as name,
"ask" should be "asks" here because "GUI Interface" is singular

2022-06-02 17:15 UTC, IslandCow commented on portfolio/src/main/webapp/index.html
> +            address,and email, and save the record in a csv file
Inconsistent spacing

2022-06-02 17:15 UTC, IslandCow commented on portfolio/src/main/webapp/index.html
> +      <!--<p>Click <a href="/hello">here</a> to see content created by server code.</p>
Instead of commenting this out, it's better to delete it. If you want to recover it later, you can look through your change history in git.

2022-06-02 17:15 UTC, IslandCow commented on portfolio/src/main/webapp/script.js
> +
Did you mean to change this?

2022-06-02 17:15 UTC, IslandCow commented on portfolio/src/main/webapp/style.css
> +
Extra space

2022-06-02 17:15 UTC, IslandCow commented on portfolio/src/main/webapp/style.css
> +#name_heading{
For the sake of consistent style, I would keep the space before the "{"

2022-06-03 05:29 UTC, IslandCow approved these changes

2022-06-03 05:29 UTC, IslandCow commented
Looks good to me

2022-06-03 23:36 UTC, merged